server:
    port: 9095

spring:
    application:
        name: bbddmongo
    data:
        mongodb:
            uri: mongodb://192.168.99.100:27018/peliculas
        
eureka:
    client:
        serviceUrl:
            defaultzone: http://localhost:8761/eureka/,http://toshiba02:8762/eureka/
    instance:
        nonSecurePortEnabled: false
        securePortEnabled: true
        metadataMap:
            appOwner: yosuer
            description: BBDD Mongo
            instanceId: ${spring.application.name}:${server.port}