server:
    port: 8761
spring:
    profiles: node1
    application:
        name: eureka-server
eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/,http://toshiba02:8762/eureka/
    instance:
        hostname: localhost
        leaseRenewalIntervalInSeconds: 10
    server:
        waitTimeInMsWhenSyncEmpty: 0
        enableSelfPreservation: true

---

server:
    port: 8762
spring:
    profiles: node2
    application:
        name: eureka-server
eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/,http://toshiba02:8762/eureka/
    instance:
        hostname: toshiba02
        leaseRenewalIntervalInSeconds: 10
    server:
        waitTimeInMsWhenSyncEmpty: 0
        enableSelfPreservation: true